
#Topics
yolo_output_image: "/yolo/image_raw"
raw_output_image: "/usb_cam/image_raw"

#Paths
source: 0 # file/dir/URL/glob/screen/0(webcam)
weights: "yolov5s.pt"  # model path or triton URL   
data: "/data/coco128.yaml"  # dataset.yaml path"

#model hyperparameters
conf_thres: 0.25 # confidence threshold
iou_thres: 0.45 # NMS IOU threshold
max_det: 1000 # maximum detections per image
device: "" # cuda device, i.e. 0 or 0,1,2,3 or cpu
agnostic_nms: False # class-agnostic NMS
augment: True # augmented inference
visualize: False # visualize features
update: False  # update all models
line_thickness: 3  # bounding box thickness (pixels)
hide_labels: False  # hide labels
hide_conf: False  # hide confidences
half: False  # use FP16 half-precision inference
dnn: False  # use OpenCV DNN for ONNX inference
vid_stride: 1  # video frame-rate stride